# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: python-publish-trigger

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.label.name, 'autorelease')) && (github.event.pull_request.user.login == "github-actions[bot]") }}
    runs-on: ubuntu-latest
    steps:
    - uses: KyoriPowered/action-regex-match@v3
      id: regex-match
      with:
        text: ${{ github.event.pull_request.title }} 
        regex: '^(chore\(main\): release).*$'
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: |
        cd python
        python -m build
    - name: Publish distribution 📦 to Test PyPI
      if: ${{ steps.regex-match.outputs.match != '' }}
      run: |
        cd python
        pip install twine
        twine upload --repository testpypi --username __token__ --password "${{secrets.TEST_PYPI_TOKEN}}" dist/*
