# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Python publish trigger

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-regex-match@v3
      id: regex-match
      with:
        text: ${{ github.event.pull_request.title }} 
        regex: '^(chore\(main\): release).*$'
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/python-publish.yml
    if: ${{ steps.regex-match.outputs.match != '' }}
